services:
  db:
    image: postgres:15-alpine
    container_name: augure_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: augure_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: augure_scraper
    volumes:
      - ./scraper:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: