import { pgTable, text, timestamp, jsonb, uuid, integer, boolean } from 'drizzle-orm/pg-core';

export const trends = pgTable('trends', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  slug: text('slug').unique().notNull(),
  description: text('description').notNull(),
  context: text('context').notNull(),
  usage_example: text('usage_example').notNull(),
  usage_keys: jsonb('usage_keys').$type<string[]>(),
  score_base: integer('score_base').default(0).notNull(),
  status: text('status').notNull(), 
  category: text('category'),
  region: text('region'),
  age_range: text('age_range'),
  image_url: text('image_url'),
  platforms: jsonb('platforms'),
  badges: jsonb('badges'),
  extra_stats: jsonb('extra_stats'),
  rank: integer('rank'),
  weakSignalsHashtags: jsonb('weak_signals_hashtags'),
  weakSignalsMusic: jsonb('weak_signals_music'),
  ageDistribution: jsonb('age_distribution'),
  originalPostAt: timestamp('original_post_at', { withTimezone: true }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  isMock: boolean('is_mock').default(false).notNull(),
});
