"""restore_snapshots_and_add_age_dist

Revision ID: 19752465aec0
Revises: b6452707afc6
Create Date: 2026-06-16 23:21:54.201269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19752465aec0'
down_revision: Union[str, None] = 'b6452707afc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trend_slug', sa.String(length=255), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trend_slug'], ['trends.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trends_snapshots_trend_slug'), 'trends_snapshots', ['trend_slug'], unique=False)
    op.drop_index('ix_favitem_col', table_name='favorite_items')
    op.drop_table('favorite_items')
    op.drop_index('ix_favcol_user', table_name='favorite_collections')
    op.drop_table('favorite_collections')
    op.add_column('trends', sa.Column('age_distribution', sa.JSON(), nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('trends', 'age_distribution')
    op.create_table('favorite_collections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=10), server_default=sa.text("'🔖'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_collections_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorite_collections_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_favcol_user', 'favorite_collections', ['user_id'], unique=False)
    op.create_table('favorite_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('trend_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['favorite_collections.id'], name='favorite_items_collection_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='favorite_items_thread_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], name='favorite_items_trend_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorite_items_pkey'),
    sa.UniqueConstraint('collection_id', 'thread_id', name='uq_favitem_col_thread'),
    sa.UniqueConstraint('collection_id', 'trend_id', name='uq_favitem_col_trend')
    )
    op.create_index('ix_favitem_col', 'favorite_items', ['collection_id'], unique=False)
    op.drop_index(op.f('ix_trends_snapshots_trend_slug'), table_name='trends_snapshots')
    op.drop_table('trends_snapshots')
    # ### end Alembic commands ###
