"""add_original_post_at_to_trends

Revision ID: 6336f9fc4eb8
Revises: 19752465aec0
Create Date: 2026-06-17 01:57:11.458460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6336f9fc4eb8'
down_revision: Union[str, None] = '19752465aec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_items')
    op.drop_index('ix_favcol_user', table_name='favorite_collections')
    op.drop_table('favorite_collections')
    op.add_column('trends', sa.Column('original_post_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('trends', 'original_post_at')
    op.create_table('favorite_collections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=10), server_default=sa.text("'🔖'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_collections_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorite_collections_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_favcol_user', 'favorite_collections', ['user_id'], unique=False)
    op.create_table('favorite_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('trend_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['favorite_collections.id'], name='favorite_items_collection_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='favorite_items_thread_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], name='favorite_items_trend_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorite_items_pkey'),
    sa.UniqueConstraint('collection_id', 'thread_id', name='uq_favitem_col_thread'),
    sa.UniqueConstraint('collection_id', 'trend_id', name='uq_favitem_col_trend')
    )
    # ### end Alembic commands ###
