"""create_banned_hashtags_table

Revision ID: 713a82e71e1b
Revises: 6336f9fc4eb8
Create Date: 2026-06-17 03:16:46.533305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713a82e71e1b'
down_revision: Union[str, None] = '6336f9fc4eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_hashtags',
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned_hashtags')
    # ### end Alembic commands ###
