"""sync_trends_schema

Revision ID: b6452707afc6
Revises: a3f1e8c20d45
Create Date: 2026-06-16 01:52:50.710103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6452707afc6'
down_revision: Union[str, None] = 'a3f1e8c20d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trends_snapshots')
    op.add_column('trends', sa.Column('weak_signals_hashtags', sa.JSON(), nullable=True))
    op.add_column('trends', sa.Column('weak_signals_music', sa.JSON(), nullable=True))
    op.alter_column('trends', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'La description de cette tendance n''est pas encore disponible. Notre équipe vous prie de l''en excuser et vous invite à revenir prochainement.'::text"))
    op.alter_column('trends', 'context',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'Le contexte de cette tendance n''est pas encore disponible. Notre équipe vous prie de l''en excuser et vous invite à revenir prochainement.'::text"))
    op.alter_column('trends', 'usage_example',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'L''exemple d''usage de cette tendance n''est pas encore disponible. Notre équipe vous prie de l''en excuser et vous invite à revenir prochainement.'::text"))
    op.alter_column('trends', 'usage_keys',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('trends', 'platforms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('trends', 'badges',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('trends', 'extra_stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('trends', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_constraint('trends_slug_key', 'trends', type_='unique')
    op.create_index(op.f('ix_trends_slug'), 'trends', ['slug'], unique=True)
    op.alter_column('users', 'target_ages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'target_networks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'target_geography',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('users', 'target_geography',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'target_networks',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'target_ages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_trends_slug'), table_name='trends')
    op.create_unique_constraint('trends_slug_key', 'trends', ['slug'])
    op.alter_column('trends', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('trends', 'extra_stats',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trends', 'badges',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trends', 'platforms',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trends', 'usage_keys',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trends', 'usage_example',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'L''exemple d''usage de cette tendance n''est pas encore disponible. Notre équipe vous prie de l''en excuser et vous invite à revenir prochainement.'::text"))
    op.alter_column('trends', 'context',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Le contexte de cette tendance n''est pas encore disponible. Notre équipe vous prie de l''en excuser et vous invite à revenir prochainement.'::text"))
    op.alter_column('trends', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'La description de cette tendance n''est pas encore disponible. Notre équipe vous prie de l''en excuser et vous invite à revenir prochainement.'::text"))
    op.drop_column('trends', 'weak_signals_music')
    op.drop_column('trends', 'weak_signals_hashtags')
    op.create_table('trends_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('trend_slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('platform', sa.TEXT(), server_default=sa.text("'unknown'::text"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trend_slug'], ['trends.slug'], name='trends_snapshots_trend_slug_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='trends_snapshots_pkey')
    )
    # ### end Alembic commands ###
