"""add is_mock flag to trends

Revision ID: cf87b587ccc2
Revises: 1d731941913c
Create Date: 2026-06-17 14:06:23.763577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf87b587ccc2'
down_revision: Union[str, None] = '1d731941913c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favcol_user', table_name='favorite_collections')
    op.create_index(op.f('ix_favorite_collections_user_id'), 'favorite_collections', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorite_items_collection_id'), 'favorite_items', ['collection_id'], unique=False)
    op.add_column('trends', sa.Column('is_mock', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'is_mock')
    op.drop_index(op.f('ix_favorite_items_collection_id'), table_name='favorite_items')
    op.drop_index(op.f('ix_favorite_collections_user_id'), table_name='favorite_collections')
    op.create_index('ix_favcol_user', 'favorite_collections', ['user_id'], unique=False)
    # ### end Alembic commands ###
