"""init

Revision ID: ec0f7c9bf290
Revises: 
Create Date: 2026-06-11 10:43:12.603372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0f7c9bf290'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_slug'), 'interests', ['slug'], unique=True)
    op.create_table('trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('usage_example', sa.Text(), nullable=False),
    sa.Column('score_base', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('VIRAL', 'EMERGENT', 'EN_HAUSSE', 'STABLE', 'EN_BAISSE', name='trend_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('COMMUNITY_MANAGER', 'PARENT', 'AGENCE', 'INFLUENCEUR', 'TEACHER', name='user_role'), nullable=True),
    sa.Column('target_generation', sa.Enum('GEN_Z', 'ALPHA', name='target_generation'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('trend_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trend_id', sa.UUID(), nullable=False),
    sa.Column('tag_type', sa.Enum('INTEREST', 'GENERATION', 'ROLE', name='tag_type'), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_tags_trend_id'), 'trend_tags', ['trend_id'], unique=False)
    op.create_table('user_interests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_trend_tags_trend_id'), table_name='trend_tags')
    op.drop_table('trend_tags')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trends')
    op.drop_index(op.f('ix_interests_slug'), table_name='interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
